### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by creydr**
Manually running the update-deps skript via
```
./hack/update-deps.sh --release 1.13 --module-release 0.40 --upgrade
```
To get the eventing-core submodule changes for 1.13 (see #178)

/cc @Cali0707 @Leo6Leo @pierDipi

### CODE REVIEW

**Review by Cali0707 — APPROVED** [review]
/lgtm
/approve

**Comment by creydr** [comment]
Need https://github.com/knative-extensions/eventing-kafka-broker/pull/3633

**Comment by creydr** [comment]
Rerun `./hack/update-deps.sh --release 1.13 --module-release 0.40 --upgrade` to get latest EKB changes

@Cali0707 @Leo6Leo can you recheck?

**Review by Cali0707 — APPROVED** [review]
/lgtm
This has the commit to skip the tests

**Pull request merged**
